### ISSUE TITLE
Register for an event - External function 

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#16] opened 2024-10-21 08:24 UTC
As someone that want to attend an event, i should be able to register for the event, 

Create a function that allow user to register for an event by specifying the eventId,

User can only register for an open event

Save the event details in the storage map

`attendee_event_details: map (attendees_id, event_registration)`

And also update the registration counter

`event_registration_couter: map(eventId, total_number_of_registration)`

Include unit test for
- Register for an event 
- Register for an event emiitted 

Provide an ETH

**Comment by blocksorcerer** [comment] 2024-10-21 18:52
Hey @mubarak23 I would like to work on this issue.

**Comment by casweeney** [comment] 2024-10-23 14:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.


### How I plan on tackling this issue
To tackle this issue:

1. I will first add a `register_for_event()` function signature in the IEvent interface.
2. I will implement the register_for` function and the function will take in `event_id` as argument.
3. Using the `event_id` I will get the event details from `event_details` mapping and assert that `is_closed` is `false`.
4. I will store the attendee event details using `attendee_event_details`mapping and also using `event_registrations` mapping I will store the `event_id` using the attendee address as key.
5. Lastly, I will increase the value of `total_attendee` by one.

6. Testing:
I will test to ensure that an `event_id` exist
I will test to ensure that an event is still open before an attendee can register
I will create an event, then test for registration and assert that the `total_attendee` value increased by one.

**Comment by MullerTheScientist** [comment] 2024-10-23 22:54
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
My Testing Approche
i will Test for successful registration
Test for event emission
Test for failure cases (closed event, duplicate registration, full event)

**Comment by PoulavBhowmick03** [comment] 2024-10-24 07:05
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.


### How I plan on tackling this issue
I will implement the register_for_event function within the Events contract. This function will first verify that the specified event_id corresponds to an open event by checking the is_closed flag in the event_details. If the event is open, the function will save the registration details in the attendee_event_details storage map, using a combination of the attendee's address and the event ID as the key. Additionally, I will increment the registration counter for the specific event in the event_registration_counter mapping to keep track of the total number of registrations. To ensure the functionality is working correctly, I will create unit tests that check for successful event registration, confirm that the appropriate event registration details are emitted, and validate that the necessary data is saved in the storage maps. 

ETA - 2 days

**Comment by manoahLinks** [comment] 2024-10-24 07:32
My background and how it can be leveraged 

I'm a proficient cairo developer,and i have built solutions around event ticketing.

**Comment by manlikeHB** [comment] 2024-10-24 07:40
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement.

### How I plan on tackling this issue
I'll create the function with all the expected functionality and write a robust test ensuring full test coverage.
ETA-2days

**Comment by Samuel1-ona** [comment] 2024-10-24 07:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

My background and how it can be leveraged
Hello a blockchain developer. I will love to work on this issue

**Comment by wheval** [comment] 2024-10-24 08:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello @mubarak23 ,  I'm Wheval, a frontend developer. I recently graduated from a Starknet Cairo Bootcamp. This would be my first contribution to the repo. I would really love to contribute and gain more experience.

### How I plan on tackling this issue
Heres how i would apprach the problm,
In the **Events** contract, I would implement the `register_for_event` function with the following steps:

1. **Retrieve Event Details**  
   The function would get the `event_details` from the `event_id` parameter. It would then assert that the `is_closed` boolean is `false`. If it is `true`, the function would panic with the message "event is closed".

2. **Map Attendee to Event Registration**  
   The function would map `(attendee_id, event_registration)` to the `attendee_event_details` in the storage. The current storage includes:  
   `attendee_event_details: map <(event_id, attendeeAddress), EventRegistration>`

3. **Create Event Registration Counter**  
   In the storage, I would add:  
   `event_registration_counter: map(eventId, total_number_of_registration)`

4. **Update Registration Counter**  
   In the `register_for_event` function, the `total_number_of_registration` from the `event_registration_counter` would be updated whenever a user successfully registers for a particular `event_id`.

5. **Emit Event**  
   The function would emit the `RegisteredForEvent` event.

6. **Unit Tests**  
   I would write unit tests for the following scenarios:
   - `register_for_event`
   - `event_is_closed`
   - `user_already_registered`
   - `zero_address_caller`
   - Also, ensure the correct event is emitted.

7. **Ensure Tests Pass**  
   I would ensure all tests are passing before making a PR.

ETA is 2 days.

**Comment by Benjtalkshow** [comment] 2024-10-24 09:51
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will implement an external function that allows users to register for an event by specifying the eventId. This function will check if the event is currently open for registration, ensuring that users can only register for events that are actively accepting attendees.

Upon successful registration, I will save the event details in the storage map called attendee_event_details, which will store the registration information for each attendee identified by their unique ID. Additionally, I will update the event_registration_counter map to reflect the total number of registrations for the specified event, allowing for easy tracking of attendee counts.

To ensure the reliability of this functionality, I will write unit tests that cover the registration process. These tests will verify that a user can successfully register for an open event and that the relevant data is stored correctly. Furthermore, I will include a test to confirm that a registration event is emitted upon successful registration, ensuring that all necessary events are tracked and logged as intended.

By implementing this feature, I will enhance the user experience by allowing seamless registration for events while maintaining accurate records of attendance. I am looking forward to delivering this functionality and will provide the implementation and tests shortly. My ETA is 6 days. Thanks you.

**Comment by ikemHood** [comment] 2024-10-26 06:51
Open for contribution?

**Closed** 2024-11-02 15:03 UTC
Labels: good first issue, ODHack9
